<?php
/** @var Meta\Catalog\Block\Adminhtml\Diagnostics $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$reports = $block->getReports();
?>

<?php if (!empty($reports)): ?>
    <style>
    #catalog-diagnostics-report th, td {
        border: 1px solid black;
    }
    #catalog-diagnostics-report th, td {
      padding: 15px;
    }
    .sample-affected-items {
        margin-bottom: 15px;
    }
    .sample-affected-items ul {
        margin-left: 15px;
    }
    .diagnostic-description {
        padding-left: 25px;
    }
    .store {
        margin-bottom: 15px;
    }
    </style>
    <select class="store">
        <?php foreach ($reports as $report): ?>
            <option value="<?= $escaper->escapeHtmlAttr($report['store_id']) ?>">
                <?= $escaper->escapeHtml(__($report['store_name'])) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <?php foreach ($reports as $report): ?>
        <?php $catalog = $report['catalog_id']; ?>
        <?php $storeId = $report['store_id']; ?>
        <table class="store-info store-<?= $escaper->escapeHtmlAttr($report['store_id']) ?>">
            <thead>
                <tr>
                    <th><?= $escaper->escapeHtml(__('Title')) ?></th>
                    <th><?= $escaper->escapeHtml(__('Severity')) ?></th>
                    <th><?= $escaper->escapeHtml(__('Type')) ?></th>
                    <th><?= $escaper->escapeHtml(__('Diagnostics Description')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($report['data'] as $item): ?>
                    <tr>
                        <td><?= $escaper->escapeHtml($item['title']) ?></td>
                        <td><?= $escaper->escapeHtml($item['severity']) ?></td>
                        <td><?= $escaper->escapeHtml($item['type']) ?></td>
                        <td class="diagnostic-description">
                            <?php $diagnostics = $item['diagnostics']; ?>
                            <ul>
                            <?php foreach ($diagnostics as $diagnostic): ?>
                                <?php $products = $block->getSampleAffectedItems($diagnostic, $catalog, $storeId); ?>
                                    <?php if ($products): ?>
                                        <li>
                                            <div>
                                                <strong>
                                                    <?= $escaper->escapeHtml(__('Description: ')) ?>
                                                </strong>
                                                <?= $escaper->escapeHtml($diagnostic['description']) ?>
                                            </div>
                                            <div>
                                                <strong>
                                                    <?= $escaper->escapeHtml(__('Type: ')) ?>
                                                </strong>
                                                <?= $escaper->escapeHtml($diagnostic['type']) ?>
                                            </div>
                                            <?php if ($diagnostic['call_to_action']): ?>
                                                <div>
                                                    <strong>
                                                        <?= $escaper->escapeHtml(__('Call to Action: ')) ?>
                                                    </strong>
                                                    <?= $escaper->escapeHtml($diagnostic['call_to_action']) ?>
                                                </div>
                                            <?php endif; ?>
                                            <div class="sample-affected-items">
                                                <strong>
                                                    <?= $escaper->escapeHtml(__('Sample affected items:')) ?>
                                                </strong>
                                                <ul>
                                                    <?php foreach ($products as $product): ?>
                                                        <?php $adminUrl = $block->getAdminUrl($product, $storeId); ?>
                                                        <li>
                                                            <?= $escaper->escapeHtml($product->getName()) ?>
                                                            (<a href="<?= $escaper->escapeHtml($adminUrl) ?>">
                                                                <?= $escaper->escapeHtml($product->getSku()) ?>
                                                            </a>)
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                        </li>
                                    <?php endif; ?>
                            <?php endforeach; ?>
                            </ul>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endforeach; ?>
<?php else: ?>
    <p><?= $escaper->escapeHtml(__('Report is not available')) ?></p>
<?php endif; ?>
