<?php
/** @var Meta\BusinessExtension\Block\Adminhtml\Email $block */
/** @var Magento\Framework\Escaper $escaper */
$emails = $block->getEmails();
?>
<?php if (!empty($emails)): ?>
    <style>
        #email-table th, td {
            border: 1px solid black;
            padding: 15px;
        }
    </style>
    <table id="email-table">
        <tr>
            <th><?= __('Email') ?></th>
            <th><?= __('Source') ?></th>
        </tr>

        <?php foreach ($emails as $item) : ?>
            <tr>
                <td><?= $escaper->escapeHtml($item['email_address']) ?></td>
                <td><?= $escaper->escapeHtml($item['source']) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <p><?= __('No emails ') ?></p>
<?php endif; ?>

