<?php /** @var Meta\BusinessExtension\Block\Adminhtml\Setup $block */ ?>
<select id="store">
    <option value=""><?= $block->escapeHtml(__('Select store')) ?></option>
    <?php foreach($block->getStores() as $key => $store): ?>
        <?php if ($key == 'admin'): ?>
            <?php continue; ?>
        <?php endif; ?>
        <option
            value="<?= $block->escapeHtmlAttr($store['store_id']) ?>"
            data-installed="<?= $block->isFBEInstalled($store['store_id']) ?>"
            data-pixel-id="<?= $block->fetchPixelId($store['store_id']) ?>"
            data-system-user-name="<?= $block->getExternalBusinessId($store['store_id']) ?>"
            data-external-business-id="<?= $block->getExternalBusinessId($store['store_id']) ?>"
        ><?= $block->escapeHtml(__($store['name'])) ?></option>
    <?php endforeach; ?>
</select>
<div>
    <div id="fbe-iframe">
    </div>
</div>

<script>
    window.facebookBusinessExtensionConfig = {
        popupOrigin: "https://business.facebook.com"
        , setPixelId: '<?= $block->getPixelAjaxRoute() ?>'
        , setAccessToken: '<?= $block->getAccessTokenAjaxRoute() ?>'
        , setProfilesData: '<?= $block->getProfilesAjaxRoute()?>'
        , saveConfig: '<?= $block->fetchConfigurationAjaxRoute() ?>'
        , fbeLoginUrl: "https://business.facebook.com/fbe-iframe-get-started/?"
        , deleteConfigKeys: '<?= $block->getDeleteAssetIdsAjaxRoute() ?>'
        , appId: '<?= $block->getAppId() ?>'
        , timeZone: 'America/Los_Angeles'
        , businessVertical: 'ECOMMERCE'
        , channel: 'DEFAULT'
        , currency: '<?= $block->getCurrencyCode() ?>'
        , businessName: 'Magento'
        , debug: true
        , setAAMSettings: '<?= $block->getAAMSettingsRoute() ?>'
    };
</script>
<script>
    require([
        'Meta_BusinessExtension/js/fbe_allinone'
    ], function () {
    });
</script>
