<?php
/**
 * @var Meta\BusinessExtension\Block\Adminhtml\Setup $block
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<?php if ($block->getSelectedStoreId() === null): ?>
    Create a Store to continue with setup.
<?php else: ?>
    <script>
        window.facebookBusinessExtensionConfig = {
            appId: '<?= $escaper->escapeHtml($block->getAppId()) ?>',
            businessName: 'Magento',
            businessVertical: 'ECOMMERCE',
            channel: 'COMMERCE',
            cleanConfigCacheUrl: '<?= $escaper->escapeHtml($block->getCleanCacheAjaxRoute()) ?>',
            currency: '<?= $escaper->escapeHtml($block->getCurrencyCode()) ?>',
            customApiKey: '<?= $escaper->escapeHtml($block->getCustomApiKey()) ?>',
            debug: true,
            deleteConfigKeys: '<?= $escaper->escapeHtml($block->getDeleteAssetIdsAjaxRoute()) ?>',
            externalBusinessId: '<?=
                $escaper->escapeHtml($block->getExternalBusinessId($block->getSelectedStoreId()))
            ?>',
            fbeAccessTokenUrl: '<?= $escaper->escapeHtml($block->getFbeAccessTokenUrl()) ?>',
            fbeInstallsConfigUrl: '<?= $escaper->escapeHtml($block->getFbeInstallsConfigUrl()) ?>',
            fbeInstallsSaveUrl: '<?= $escaper->escapeHtml($block->getFbeInstallsSaveUrl()) ?>',
            fbeLoginUrl: "https://business.facebook.com/fbe-iframe-get-started/?",
            installed: '<?=
                $escaper->escapeHtml($block->isFBEInstalled($block->getSelectedStoreId())) ? 'true' : 'false'
            ?>',
            isCommerceEmbeddedExtensionEnabled: <?=$block->isCommerceExtensionEnabled() ? 'true' : 'false'?>,
            pixelId: '<?= $escaper->escapeHtml($block->fetchPixelId($block->getSelectedStoreId())) ?>',
            popupOrigin: "https://business.facebook.com",
            postFBEOnboardingSync: '<?= $escaper->escapeHtml($block->fetchPostFBEOnboardingSyncAjaxRoute()) ?>',
            saveConfig: '<?= $escaper->escapeHtml($block->fetchConfigurationAjaxRoute()) ?>',
            setAAMSettings: '<?= $escaper->escapeHtml($block->getAAMSettingsRoute()) ?>',
            setAccessToken: '<?= $escaper->escapeHtml($block->getAccessTokenAjaxRoute()) ?>',
            setInstalledFeatures: '<?= $escaper->escapeHtml($block->getInstalledFeaturesAjaxRouteUrl()) ?>',
            setPixelId: '<?= $escaper->escapeHtml($block->getPixelAjaxRoute()) ?>',
            setProfilesData: '<?= $escaper->escapeHtml($block->getProfilesAjaxRoute()) ?>',
            storeId: '<?= $escaper->escapeHtml($block->getSelectedStoreId()) ?>',
            systemUserName: '<?=
                $escaper->escapeHtml($block->getExternalBusinessId($block->getSelectedStoreId()))
            ?>',
            timeZone: 'America/Los_Angeles'
        }
    </script>
    <?php if ($block->isCommerceExtensionEnabled() && $block->isFBEInstalled($block->getSelectedStoreId())): ?>
        <iframe
                id="commerce-extension-iframe"
                src="<?=
                    $escaper->escapeHtmlAttr($block->getCommerceExtensionIFrameURL($block->getSelectedStoreId()))
                ?>"
                scrolling="no"
                style="border: 0; width: 100%; min-height:50vh;"></iframe>
        <script>
            require([
                'jquery',
                'Meta_BusinessExtension/js/commerce_extension_allinone'
            ], function ($) {
            });
        </script>
    <?php else: ?>
        <div>
            <div id="fbe-iframe">
            </div>
        </div>
        <script>
            require([
                'jquery',
                'Meta_BusinessExtension/js/fbe_allinone',
                'Meta_BusinessExtension/js/fbe_installs'
            ], function ($, fbeAllInOne, fbeInstalls) {
                fbeInstalls.startFBEInstallsProcess();
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
