<?php
/**
 * @var \Meta\Sales\Block\Adminhtml\Order\View\Tab\Facebook $block
 */

$optInFlag = $block->isEmailRemarketingAllowedForOrder() ? 'Yes' : 'No';

?>

<section class="admin__page-section order-facebook">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Facebook')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php if ($block->isFacebookOrder()): ?>
            <div class="admin__page-section-item order-facebook-details">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Details')) ?></span>
                </div>
                <address class="admin__page-section-item-content">
                    <p><b>Magento order #</b>: <?= $block->getOrder()->getIncrementId() ?></p>
                    <p><b>Facebook order #</b>: <?= $block->getOrder()->getExtensionAttributes()->getFacebookOrderId() ?></p>
                    <p><b>Channel</b>: <?= $block->getOrder()->getExtensionAttributes()->getChannel() ?></p>
                    <p><b>Customer marketing opt-in</b>: <?= $optInFlag ?></p>
                    <p><b><a href="<?= $block->escapeUrl($block->getOrderFacebookUrl()) ?>" target="_blank">Manage in Commerce Manager</a></b></p>
                </address>
            </div>
        <?php else: ?>
            <div class="admin__page-section-item order-not-a-facebook-order">
                <?= __('Not a Meta order') ?>
            </div>
        <?php endif; ?>
    </div>
</section>
