<?php
/**
 * @var $block \Meta\BusinessExtension\Block\Adminhtml\System\Config\DeleteConnection
 * @var $escaper \Magento\Framework\Escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
    $scriptString = <<<script
        require([
            'jquery',
            'prototype'
        ], function (jQuery) {
            const resultBlock = jQuery('#fb_delete_connection_result');
            const responseToggle = jQuery('#fb_delete_connection_result_response_toggle');
            const responseTextBlock = jQuery('#fb_delete_connection_result_response');

            responseToggle.click(function () {
                responseTextBlock.toggle();
            });

            jQuery('#fb_delete_connection_btn').click(function () {
                const text = "Warning: Are you sure you want to delete the connection?" +
                    "If you do, your store will no longer be connected to Meta " +
                    "and you will need to reconnect your assets to restore the connection.";
                if (!confirm(text)) {
                    return;
                }
                const params = {};
                new Ajax.Request('{$escaper->escapeUrl($block->getAjaxUrl())}', {
                    parameters: params,
                    loaderArea: false,
                    asynchronous: true,
                    onCreate: function () {
                        resultBlock.find('.fb-delete-connection-finished').hide();
                        resultBlock.find('.fb-delete-connection-processing').show();
                        jQuery('#fb_delete_connection_result_text').text('');
                        responseToggle.hide();
                        responseTextBlock.hide();
                    },
                    onSuccess: function (response) {
                        resultBlock.find('.fb-delete-connection-processing').hide();

                        let resultText = '';
                        let resultResponse = '';
                        if (response.status > 200) {
                            resultText = response.statusText;
                        } else {
                            resultResponse = ' (' + response.responseText + ')';
                            resultText = 'Finished';
                            resultBlock.find('.fb-delete-connection-finished').show();
                        }
                        jQuery('#fb_delete_connection_result_text').text(resultText);
                        jQuery('#fb_delete_connection_result_response').text(resultResponse);
                        responseToggle.show();

                        new Ajax.Request('{$escaper->escapeUrl($block->getCleanCacheAjaxUrl())}', {
                            asynchronous: true
                        });
                    }
                });
            });

        });
    script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $scriptString, false); ?>
<?= $block->getButtonHtml() ?>
<span id="fb_delete_connection_result">
    <img class="fb-delete-connection-processing" hidden="hidden" alt="Processing" style="margin:0 5px" src=
    "<?= $escaper->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"
    />
    <img class="fb-delete-connection-finished" hidden="hidden" alt="Finished" style="margin:-3px 5px" src=
    "<?= $escaper->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"
    />
    <span id="fb_delete_connection_result_text"></span>
    <span id="fb_delete_connection_result_response_toggle"
          style="display: none;
          cursor: pointer;
          color: #888a85;
          text-decoration: underline;">(response)</span>
    <div id="fb_delete_connection_result_response"
         style="display: none;
         color: #888a85;
         font-size: 13px;
         max-width: 459px;
         margin: 2px 0;"></div>
</span>

<p class="note">
    <span>
        <?= __(/* @noEscape */ 'Warning: This will delete the connection
        to Meta assets and reset the local configuration.') ?>
    </span>
</p>
