<?php
/**
 * @var \Meta\BusinessExtension\Block\Adminhtml\System\Config\ModuleInfo $block
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div>
    <p>Version: <?= $escaper->escapeHtml($block->getModuleVersion()) ?></p>
    <p>Pixel ID: <?= $escaper->escapeHtml($block->getPixelId()) ?></p>
    <p><a target="_blank"
          href="<?= $escaper->escapeUrl($block->getEventsManagerUrl()) ?> ">
            <?= $escaper->escapeHtml(__('Events Manager')) ?>
        </a>
    </p>
</div>
