<?php /* @var $block \Meta\Sales\Block\Adminhtml\System\Config\PullOrders */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        const resultBlock = jQuery('#fb_pull_orders_result');
        const responseToggle = jQuery('#fb_pull_orders_result_response_toggle');
        const responseTextBlock = jQuery('#fb_pull_orders_result_response');

        responseToggle.click(function () {
            responseTextBlock.toggle();
        });

        jQuery('#fb_pull_orders_btn').click(function () {
            const params = {};
            new Ajax.Request('<?= $block->escapeUrl($block->getAjaxUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultBlock.find('.fb-pull-orders-finished').hide();
                    resultBlock.find('.fb-pull-orders-processing').show();
                    jQuery('#fb_pull_orders_result_text').text('');
                    responseToggle.hide();
                    responseTextBlock.hide();
                },
                onSuccess: function (response) {
                    resultBlock.find('.fb-pull-orders-processing').hide();

                    let resultText = '';
                    let resultResponse = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultResponse = ' (' + response.responseText + ')';
                        resultText = 'Finished';
                        resultBlock.find('.fb-pull-orders-finished').show();
                    }
                    jQuery('#fb_pull_orders_result_text').text(resultText);
                    jQuery('#fb_pull_orders_result_response').text(resultResponse);
                    responseToggle.show();
                }
            });
        });

    });
</script>

<?= /* @noEscape */ $block->getButtonHtml() ?>
<span id="fb_pull_orders_result">
    <img class="fb-pull-orders-processing" hidden="hidden" alt="Processing" style="margin:0 5px" src=
        "<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"
    />
    <img class="fb-pull-orders-finished" hidden="hidden" alt="Finished" style="margin:-3px 5px"  src=
        "<?= $block->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"
    />
    <span id="fb_pull_orders_result_text"></span>
    <span id="fb_pull_orders_result_response_toggle"
          style="display: none;
          cursor: pointer;
          color: #888a85;
          text-decoration: underline;">(response)</span>
    <div id="fb_pull_orders_result_response"
         style="display: none;
         color: #888a85;
         font-size: 13px;
         max-width: 459px;
         margin: 2px 0;"></div>
</span>
