<?php
/**
 * @var \Meta\Conversion\Block\Pixel\AddPaymentInfo $block
 * @var $escaper \Magento\Framework\Escaper
 */
$trackerUrl = $block->getTrackerUrl();
?>
<?php if ($block->getFacebookPixelID()) { ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Meta_Conversion/js/addPaymentInfo": {
                    "url" : "<?= $escaper->escapeUrl($trackerUrl); ?>",
                    "payload": <?= /* @noEscape */
                    json_encode([
                    "eventName" => $escaper->escapeHtml($block->getEventToObserveName())
                    ]) ?>,
                    "browserEventData": <?= /* @noEscape */
                    json_encode([
                    'fbAgentVersion' => $escaper->escapeHtml($block->getFacebookAgentVersion()),
                    'fbPixelId' => $escaper->escapeHtml($block->getFacebookPixelID()),
                    'source' => $escaper->escapeHtml($block->getSource()),
                    'pluginVersion' => $escaper->escapeHtml($block->getPluginVersion()),
                    'track' => 'track',
                    'event' => 'AddPaymentInfo',
                    'payload' => [
                    'currency' => $escaper->escapeHtml($block->getCurrency())
                    ]
                    ]) ?>
        }
    }
}
    </script>
<?php } ?>
