<?php /** @var \Meta\Conversion\Block\Pixel\AddToCart $block */ ?>
<?php if ($block->getFacebookPixelID()) { ?>
    <script>
        require([
            'jquery'
        ], function ($) {

            function trackAddToCart(content_ids, content_name, content_category, value, eventId) {
                fbq(
                    'set',
                    'agent',
                    '<?= /* @noEscape */ $block->getFacebookAgentVersion() ?>',
                    '<?= /* @noEscape */ $block->getFacebookPixelID() ?>'
                );
                fbq('track', 'AddToCart', {
                        source: "<?= /* @noEscape */ $block->getSource() ?>",
                        pluginVersion: "<?= /* @noEscape */ $block->getPluginVersion() ?>",
                        content_type: "<?= /* @noEscape */ $block->getContentType() ?>",
                        currency: "<?= /* @noEscape */ $block->getCurrency() ?>",
                        content_ids: content_ids,
                        content_name: content_name,
                        content_category: content_category,
                        value: value
                    },
                    {
                        eventID: eventId
                    }
                );
            }

            var product_info_url = '<?= /* @noEscape */ $block->getProductInfoUrl() ?>';

            $(document).on('ajax:addToCart', function (event, data) {
                if (!data.response.backUrl) {
                    // check product data from swatch widget
                    var swatchData = $('[data-role=swatch-options]').data('mage-SwatchRenderer');
                    if (swatchData) {
                        var simpleProductId = swatchData.getProductId();
                    } else {
                        // In case product is added from category page get options using added product's id
                        // Get id of last added product
                        var productId = data.productIds[data.productIds.length - 1];
                        var categorySwatchData = $('[data-role=swatch-option-'+productId+']')
                            .data('mage-SwatchRenderer');
                        if (categorySwatchData) {
                            var simpleProductId = categorySwatchData.getProductId();
                        } else {
                            // else check product data from configurable options
                            var configurableProduct = data.form.data().mageConfigurable;
                            if(configurableProduct) {
                                var simpleProductId = configurableProduct.simpleProduct;
                            }
                        }
                    }
                    // otherwise use the product sku
                    var product_sku = data.sku;
                    var form_key = jQuery("[name='form_key']").val();
                    $.ajax({
                        url: product_info_url,
                        data: {
                            product_sku: product_sku,
                            product_id: simpleProductId,
                            form_key: form_key
                        },
                        type: 'get',
                        dataType: 'json',
                        success: function (res) {
                            trackAddToCart(
                                [res.id],
                                res.name,
                                res.content_category,
                                res.value,
                                res.event_id
                            );
                        }
                    });
                }
            });
        });
    </script>
<?php } ?>
