<?php
/**
 * @var \Meta\Conversion\Block\Pixel\CustomizeProduct $block
 * @var $escaper \Magento\Framework\Escaper
 */
$trackerUrl = $block->getTrackerUrl();
?>
<?php if ($block->getFacebookPixelID()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Meta_Conversion/js/customizeProduct": {
                    "url" : "<?= $escaper->escapeUrl($trackerUrl); ?>",
                "payload": <?= /* @noEscape */
                json_encode([
                "eventName" => $block->getEventToObserveName()
                ]) ?>,
                "browserEventData": <?= /* @noEscape */
                json_encode([
                'fbAgentVersion' => $block->getFacebookAgentVersion(),
                'fbPixelId' => $block->getFacebookPixelID(),
                'source' => $block->getSource(),
                'pluginVersion' => $block->getPluginVersion(),
                'track' => 'track',
                'event' => 'CustomizeProduct',
                'payload' => [
                'currency' => $block->getCurrency()
                ]
                ]) ?>
        }
    }
}
    </script>
<?php endif; ?>
