<?php /** @var \Meta\Conversion\Block\Pixel\Head $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->getFacebookPixelID()) { ?>
<!-- Meta Business Extension for Magento 2 -->
<!-- Meta Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');
    <?php
    $dataProcessingOptionsCode = $block->getDataProcessingOptionsJSCode();
    if (strlen($dataProcessingOptionsCode) > 0) {
        echo $escaper->escapeJs($dataProcessingOptionsCode . "\n");
    }
    ?>
fbq(
  'init',
  '<?= /* @noEscape */ $block->getFacebookPixelID() ?>',
    <?= /* @noEscape */ $block->getPixelInitCode() ?>,
  {agent: '<?= /* @noEscape */ $block->getFacebookAgentVersion() ?>' }
);
fbq('track', 'PageView', {
  source: "<?= /* @noEscape */ $block->getSource() ?>",
  pluginVersion: "<?= /* @noEscape */ $block->getPluginVersion() ?>"
});
</script>
<!-- End Meta Pixel Code -->
<?php } else { ?>
<!-- NO Pixel ID is configured, please goto Admin -->
<script>
console.log(
    'No Meta pixel is configured, please log in as a admin and then visit Stores -> Meta -> Setup -> Get Started'
);
</script>
<?php } ?>
