<?php
/** @var \Meta\Conversion\Block\Pixel\Search $block */
if ($block->getFacebookPixelID()) {
    $eventId = \Meta\Conversion\Helper\EventIdGenerator::guidv4();
    $block->trackServerEvent($eventId);
?>
    <script>
        fbq('set', 'agent', '<?= $block->getFacebookAgentVersion() ?>', '<?= $block->getFacebookPixelID() ?>');
        fbq('track', 'Search', {
                source: "<?= $block->getSource() ?>",
                pluginVersion: "<?= $block->getPluginVersion() ?>",
                search_string: "<?= $block->getSearchQuery() ?>"
            }
            , {
                eventID: "<?= $eventId ?>"
            }
        );
    </script>
    <?php $block->logEvent($block->getFacebookPixelID(), 'Search') ?>
<?php } ?>
