<?php
/** @var \Meta\Conversion\Block\Pixel\Search $block */

$trackerUrl = $block->getTrackerUrl();

if ($block->getFacebookPixelID()) {
    ?>

    <script type="text/x-magento-init">
        {
            "*": {
                "Meta_Conversion/js/metaPixelTracker" : {
                    "url" : "<?= $block->escapeHtml($trackerUrl); ?>",
                    "payload": <?= /* @noEscape */ json_encode([
                        "eventName" => $block->escapeHtml($block->getEventToObserveName()),
                        "searchQuery" => $block->escapeHtml($block->getSearchQuery())
                    ]) ?>,
                    "browserEventData": <?= /* @noEscape */ json_encode([
                        'fbAgentVersion' => $block->escapeHtml($block->getFacebookAgentVersion()),
                        'fbPixelId' => $block->escapeHtml($block->getFacebookPixelID()),
                        'source' => $block->escapeHtml($block->getSource()),
                        'pluginVersion' => $block->escapeHtml($block->getPluginVersion()),
                        'track' => 'track',
                        'event' => 'Search',
                        'payload' => ['search_string' => $block->escapeHtml($block->getSearchQuery())]
                    ]) ?>
                }
            }
        }
    </script>
<?php } ?>
