<?php
/** @var \Meta\Conversion\Block\Pixel\ViewCategory $block */

$trackerUrl = $block->getTrackerUrl();

if ($block->getFacebookPixelID()) {
    ?>

    <script type="text/x-magento-init">
        {
            "*": {
                "Meta_Conversion/js/metaPixelTracker" : {
                    "url" : "<?= $block->escapeJs($trackerUrl); ?>",
                    "payload": <?= json_encode([
                        "eventName" => $block->getEventToObserveName(),
                        "categoryId" => $block->getCategoryId(),
                    ]) ?>,
                    "browserEventData": <?= json_encode([
                        'fbAgentVersion' => $block->getFacebookAgentVersion(),
                        'fbPixelId' => $block->getFacebookPixelID(),
                        'source' => $block->getSource(),
                        'pluginVersion' => $block->getPluginVersion(),
                        'track' => 'trackCustom',
                        'event' => 'ViewCategory',
                        'payload' => ['category_name' => $block->getCategoryName() ]
                    ]) ?>
                }
            }
        }
    </script>
<?php } ?>
