<?php
/**
 * @var \Meta\Conversion\Block\Pixel\ViewContact $block
 * @var $escaper \Magento\Framework\Escaper
 */
$trackerUrl = $block->getTrackerUrl();
?>
<?php if ($block->getFacebookPixelID()) { ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Meta_Conversion/js/contactPixel": {
                    "url" : "<?= $escaper->escapeUrl($trackerUrl); ?>",
                "payload": <?= /* @noEscape */
                json_encode([
                "eventName" => $escaper->escapeHtml($block->getEventToObserveName()),
                "content_type" => $escaper->escapeHtml($block->getContentType())
                ]) ?>,
                "browserEventData": <?= /* @noEscape */
                json_encode([
                'fbAgentVersion' => $escaper->escapeHtml($block->getFacebookAgentVersion()),
                'fbPixelId' => $escaper->escapeHtml($block->getFacebookPixelID()),
                'source' => $escaper->escapeHtml($block->getSource()),
                'pluginVersion' => $escaper->escapeHtml($block->getPluginVersion()),
                'track' => 'track',
                'event' => 'Contact',
                'payload' => [
                "content_type" => $escaper->escapeHtml($block->getContentType())
                ]
                ]) ?>
        }
    }
}
    </script>
<?php } ?>
