<?php
/**
 * @var Meta\Catalog\Block\Adminhtml\System\Config\ProductFeed $block
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        const resultBlock = jQuery('#fb_feed_upload_result');
        const responseToggle = jQuery('#fb_feed_upload_result_response_toggle');
        const responseTextBlock = jQuery('#fb_feed_upload_result_response');

        responseToggle.click(function () {
            responseTextBlock.toggle();
        });

        jQuery('#fb_feed_upload_btn').click(function () {
            const params = {};
            new Ajax.Request('<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultBlock.find('.fb-feed-upload-finished').hide();
                    resultBlock.find('.fb-feed-upload-processing').show();
                    jQuery('#fb_feed_upload_result_text').text('');
                    responseToggle.hide();
                    responseTextBlock.hide();
                },
                onSuccess: function (response) {
                    resultBlock.find('.fb-feed-upload-processing').hide();

                    let resultText = '';
                    let resultResponse = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultResponse = ' (' + response.responseText + ')';
                        resultText = 'Finished';
                        resultBlock.find('.fb-feed-upload-finished').show();
                    }
                    jQuery('#fb_feed_upload_result_text').text(resultText);
                    jQuery('#fb_feed_upload_result_response').text(resultResponse);
                    const json = response.responseJSON;
                    responseToggle.show();
                }
            });
        });

    });
</script>

<?= $block->getButtonHtml() ?>
<span id="fb_feed_upload_result">
    <img class="fb-feed-upload-processing" hidden="hidden" alt="Processing" style="margin:0 5px"
         src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <img class="fb-feed-upload-finished" hidden="hidden" alt="Finished" style="margin:-3px 5px"
         src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"/>
    <span id="fb_feed_upload_result_text"></span>
    <span id="fb_feed_upload_result_response_toggle"
          style="display: none; cursor: pointer; color: #888a85; text-decoration: underline;">(response)</span>
    <div id="fb_feed_upload_result_response"
         style="display: none; color: #888a85; font-size: 13px; max-width: 459px; margin: 2px 0;"></div>
</span>
<p class="note">
    <span>Upload products from <?= $escaper->escapeHtml($block->getStoreNameForComment()) ?> to Meta</span>
</p>
